{{- if and (empty .Values.worker.pod.env.cacheUrl) (empty .Values.vote.pod.env.cacheUrl) }}
apiVersion: v1
data:
  CACHE_URL: cmVkaXMtMC5yZWRpcy1zZXJ2aWNl
kind: Secret
metadata:
  name: apps-cache-secret
{{- end }}
