apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: init-databases
          image: busybox
          command:
            - sh
            - "-c"
            - |
              until nc -z redis-0.redis-service 6379; do
                sleep 2;
              done;
              echo "Redis is up"
              until nc -z db-0.db-service 5432; do
                sleep 2;
              done;
              echo "Database is up"
      containers:
        - image: kerolosayman308/voting-app-env:examplevotingapp_worker
          name: worker
          envFrom:
            - secretRef:
                name: apps-cache-secret
            - secretRef:
                name: apps-db-secret
          resources:
            requests:
              cpu: "100m"
              memory: 100Mi
