apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:alpine
          name: redis
          readinessProbe:
            exec:
              command:
                - /healthchecks/redis.sh
            failureThreshold: 5
            periodSeconds: 5
            initialDelaySeconds: 2
          ports:
            - name: redisPort
              containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 0.1m
              requests: 100Mi
