apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: health-cm
          configMap:
            name: redis-health-cm
            defaultMode: 0777
      containers:
        - image: redis:alpine
          name: redis
          volumeMounts:
            - name: health-cm
              mountPath: /healthchecks/redis.sh
              subPath: redis.sh

          readinessProbe:
            exec:
              command:
                - /healthchecks/redis.sh
            failureThreshold: 5
            periodSeconds: 5
            initialDelaySeconds: 2
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: "0.1"
              memory: 100Mi
